version: "3"
services:
  api:
    build: ./app
    ports: 
      - "8000:8000"
    volumes:
      - .:/home/app/db
    networks:
      - staff-tracker
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - 3306:3306
    volumes:
      - my-datavolume:/var/lib/mysql
    networks:
      - staff-tracker
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  my-datavolume:
networks:
  staff-tracker:
    driver: bridge
    